export const Users = [
    {
      id:1,
      profilePicture: "assets/person/friend.png",
      username: "Mikasa Ackerman",
    },
    {
      id:2,
      profilePicture: "assets/person/friend1.png",
      username: "Eren Jaeger",
    },
    {
      id:3,
      profilePicture: "assets/person/friend2.jpeg",
      username: "Midoriya Izuku",
    },
    {
      id:4,
      profilePicture: "assets/person/friend3.jpg",
      username: "Daenerys Targaryen",
    },
    {
      id:5,
      profilePicture: "assets/person/friend4.jpg",
      username: "Jon Snow",
    },
    {
      id:6,
      profilePicture: "assets/person/friend5.png",
      username: "Levi Ackerman",
    },
    {
      id:7,
      profilePicture: "assets/person/friend6.jpg",
      username: "Monkey D Luffy",
    },
    {
      id:8,
      profilePicture: "assets/person/friend7.png",
      username: "Hange Zoe",
    },
    {
      id:9,
      profilePicture: "assets/person/friend8.jpg",
      username: "Nobara Kugisaki",
    },
    {
      id:10,
      profilePicture: "assets/person/friend9.jpg",
      username: "Satoru Gojo",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Believe In Your Own Power.",
      photo: "assets/posts/1.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      desc: "Tatakae.",
      photo: "assets/posts/8.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      photo: "assets/posts/6.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/posts/4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/posts/5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/posts/7.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/posts/10.png",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/posts/2.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      photo: "assets/posts/9.png",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      desc: "I’ve always been a nice guy who cares for my students.",
      photo: "assets/posts/3.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];